// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ciuhkkmuvqoepohihofs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNpdWhra211dnFvZXBvaGlob2ZzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzNTMyODEsImV4cCI6MjA2MTkyOTI4MX0.fAmeFKnHFiL_M6vLAY78j36Op_7RNs8Xxl4EYy0-v48";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);